apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: odh-dashboard
  app.kubernetes.io/part-of: odh-dashboard
resources:
  - role.yaml
  - cluster-role.yaml
  - service-account.yaml
  - role-binding.yaml
  - cluster-role-binding.yaml
  - auth-delegator.clusterrolebinding.yaml
  - cluster-monitoring-role-binding.yaml
  - deployment.yaml
  - routes.yaml
  - service.yaml
  - oauth.secret.yaml
  - fetch-builds-and-images.rbac.yaml
  - image-puller.clusterrolebinding.yaml
  - model-serving-role.yaml
  - model-serving-role-binding.yaml
  - fetch-accelerators.rbac.yaml
images:
  - name: odh-dashboard
    newName: quay.io/opendatahub/odh-dashboard
    newTag: main
  - name: oauth-proxy
    newName: registry.redhat.io/openshift4/ose-oauth-proxy
    digest: sha256:5698ac3043ff921b8442ba4971717110a54b53de02ca0f03a42170bd1a6940b5
